// Mocks generated by Mockito 5.4.4 from annotations
// in evm_wallet_core/test/x_wallet/x_wallet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i7;

import 'package:evm_wallet_core/src/core/chain.dart' as _i3;
import 'package:evm_wallet_core/src/core/hd_wallet.dart' as _i8;
import 'package:evm_wallet_core/src/core/transaction_detail.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:web3dart/web3dart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEthPrivateKey_0 extends _i1.SmartFake implements _i2.EthPrivateKey {
  _FakeEthPrivateKey_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Chain].
///
/// See the documentation for Mockito's code generation for more information.
class MockChain extends _i1.Mock implements _i3.Chain {
  MockChain() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> getWalletBalance({required String? address}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWalletBalance,
          [],
          {#address: address},
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getWalletBalance,
            [],
            {#address: address},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i6.TransactionDetail?> getTransactionDetail(
          {required String? txHash}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionDetail,
          [],
          {#txHash: txHash},
        ),
        returnValue: _i4.Future<_i6.TransactionDetail?>.value(),
      ) as _i4.Future<_i6.TransactionDetail?>);

  @override
  _i4.Future<BigInt> estimateGas({
    String? senderAddress,
    String? toAddress,
    BigInt? value,
    BigInt? gasPrice,
    BigInt? maxPriorityFeePerGas,
    BigInt? maxFeePerGas,
    _i7.Uint8List? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateGas,
          [],
          {
            #senderAddress: senderAddress,
            #toAddress: toAddress,
            #value: value,
            #gasPrice: gasPrice,
            #maxPriorityFeePerGas: maxPriorityFeePerGas,
            #maxFeePerGas: maxFeePerGas,
            #data: data,
          },
        ),
        returnValue: _i4.Future<BigInt>.value(_i5.dummyValue<BigInt>(
          this,
          Invocation.method(
            #estimateGas,
            [],
            {
              #senderAddress: senderAddress,
              #toAddress: toAddress,
              #value: value,
              #gasPrice: gasPrice,
              #maxPriorityFeePerGas: maxPriorityFeePerGas,
              #maxFeePerGas: maxFeePerGas,
              #data: data,
            },
          ),
        )),
      ) as _i4.Future<BigInt>);

  @override
  _i4.Future<BigInt> getChainId() => (super.noSuchMethod(
        Invocation.method(
          #getChainId,
          [],
        ),
        returnValue: _i4.Future<BigInt>.value(_i5.dummyValue<BigInt>(
          this,
          Invocation.method(
            #getChainId,
            [],
          ),
        )),
      ) as _i4.Future<BigInt>);

  @override
  _i4.Future<String> sendRawTransaction(
          {required _i7.Uint8List? signedTransaction}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRawTransaction,
          [],
          {#signedTransaction: signedTransaction},
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #sendRawTransaction,
            [],
            {#signedTransaction: signedTransaction},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<int> getNonce({required String? address}) => (super.noSuchMethod(
        Invocation.method(
          #getNonce,
          [],
          {#address: address},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i7.Uint8List> signTransaction({
    required _i2.Credentials? cred,
    required _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signTransaction,
          [],
          {
            #cred: cred,
            #transaction: transaction,
          },
        ),
        returnValue: _i4.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i4.Future<_i7.Uint8List>);
}

/// A class which mocks [HDWallet].
///
/// See the documentation for Mockito's code generation for more information.
class MockHDWallet extends _i1.Mock implements _i8.HDWallet {
  MockHDWallet() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EthPrivateKey get credential => (super.noSuchMethod(
        Invocation.getter(#credential),
        returnValue: _FakeEthPrivateKey_0(
          this,
          Invocation.getter(#credential),
        ),
      ) as _i2.EthPrivateKey);

  @override
  String getAddress() => (super.noSuchMethod(
        Invocation.method(
          #getAddress,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getAddress,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<_i7.Uint8List> getPrivateKey() => (super.noSuchMethod(
        Invocation.method(
          #getPrivateKey,
          [],
        ),
        returnValue: _i4.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i4.Future<_i7.Uint8List>);
}
